### ISSUE TITLE
Run Time Error 1004

### ISSUE THREAD

**Issue by bobvee** [scipio314/draftKnight#10]
I am unable to refresh injury and point projections.  Whenever I hit the button I receive the error "Run-time Error '1004': No data was selected to parse."

**Comment by scipio314** [comment]
Have you tried this: https://github.com/scipio314/draftKnight/issues/8  

If that doesn't work send me your spreadsheet

**Comment by bobvee** [comment]
Attempting to log in let's me get to the login screen but there is no way to input my username/password.  
![capture](https://user-images.githubusercontent.com/32209157/30766788-8869103c-9fc5-11e7-8194-626729ccf74c.JPG)

**Comment by scipio314** [comment]
It's hard to select the fields, but click the top line (below where it says "or") and start typing your username then use tab and enter your password

**Comment by bobvee** [comment]
That worked.  Thanks!   Projections were refreshed and I was able to build lineups.

**Comment by scipio314** [comment]
okay good to hear. I think FantasyPros now requires logins or something and it has made the projections part a pain
