### ISSUE TITLE
Lineup Generator Error

### ISSUE THREAD

**Issue by tikitiger** [scipio314/draftKnight#11]
![capture](https://user-images.githubusercontent.com/13833502/30771279-2eac15d8-a076-11e7-8ecc-0ace54ea9464.PNG)

**Comment by scipio314** [comment]
can you send me the spreadsheet that you have. I haven't seen this error.

**Comment by tikitiger** [comment]
[draftKnight.zip](https://github.com/scipio314/draftKnight/files/1326380/draftKnight.zip)

**Comment by scipio314** [comment]
I think i know why. you didn't download the player pool from draftkings. follow instructions here:  https://github.com/scipio314/draftKnight/wiki/-1.0--Downloading-the-DraftKings-Player-Pool
