### ISSUE TITLE
error creating linups

### ISSUE THREAD

**Issue by paqratst1** [scipio314/draftKnight#12]
I'm getting this error. 
![image](https://user-images.githubusercontent.com/33078698/31978517-0fbd4632-b8ff-11e7-8d3e-fd2380649735.png)

**Comment by paqratst1** [comment]
[draftKnight (2).zip](https://github.com/scipio314/draftKnight/files/1413134/draftKnight.2.zip)

**Comment by paqratst1** [comment]
![image](https://user-images.githubusercontent.com/33078698/31979077-09286cc2-b902-11e7-960b-a2f5b2a1976b.png)
I'm getting this one as well if not the above one

**Comment by scipio314** [comment]
Thanks for letting me know. This is a common problem and has a simple fix. The error usually occurs when the added player pool is smaller than the previous weeks.

Open up the "All Players" tab (right click on the bottom and select unhide).  
Then down at the bottom you will see some additional rows with errors in them. Delete the excess rows, then resize the table to stop at the bottom of all the players.

I've re-attached the file you sent me with the table fixed.  
[draftKnight (2).zip](https://github.com/scipio314/draftKnight/files/1414409/draftKnight.2.zip)  

Also, if you want to hide the pop ups about player status you can do that by going to the "review" section of the excel ribbon up top then selecting "show all comments".

**Comment by paqratst1** [comment]
thank you so much for the quick reply. i was a little lost when it said to delete the empty fields in the all players tab. i didn't think to see if sheets were hidden. thank you

**Comment by scipio314** [comment]
no problem, good luck this weekend!

**Comment by scipio314** [comment]
#7
