### ISSUE TITLE
Opensolver could not find an optimal solution

### ISSUE THREAD

**Issue by sosopjop** [scipio314/draftKnight#15]
Hey Scipio, I appreciate all the time and effort you have put into this project and look forward to using it. Like a previous issue, I am receiving the error that an optimal solution could not be found. In your previous post, you mentioned going to the "all players tab" and deleting any blanks. However, I can not find an "all players tab". Also, when updating the sheet for injuries and projections, it will only pull the projection for RB1 and no other player, regardless of using custom projections or built in projections,  I image the issues are related? I hope you can point me in the right direction.

I appreciate your time

![capture1](https://user-images.githubusercontent.com/35552940/35081377-20e27486-fbd1-11e7-9d0e-bfcd0da6e048.PNG)
![capture4](https://user-images.githubusercontent.com/35552940/35081380-2507802e-fbd1-11e7-8ed6-d7e55bd5faf9.PNG)
![capture3](https://user-images.githubusercontent.com/35552940/35081381-251c7402-fbd1-11e7-94cb-39386ce565c0.PNG)

**Comment by sosopjop** [comment]
I thought I had unhide all sheets, but I didn't I have no located tab and will get back after playing with it

**Comment by sosopjop** [comment]
I got it! Thank you

**Comment by scipio314** [comment]
glad you figured it out! i should add to the error message about unhiding the tabs at the bottom
