### ISSUE TITLE
Add ability to set exposure percentages to players when creating optimized line-ups

### ISSUE THREAD

**Issue by lostless13** [scipio314/draftKnight#6]
When creating line-ups people want to set % exposure to players. 

One possible implementation:
Have a column on "My Team" sheet where players can set exposure % to a given player.
Map % exposure to all players page
When running optimizer update a column for % exposure to the given player given the number of iterations.
Add a constraint to opensolver that % exposure must be <= to set exposure.

Could also simplify the eliminate a player by using this constraint to effectively eliminate players from the model by setting % exposure to 0.

**Comment by scipio314** [comment]
This feature has been added in version 1.7
