### ISSUE TITLE
the objective cell appears to contain an error

### ISSUE THREAD

**Issue by pherny** [scipio314/draftKnight#7]
I keep getting the error message in the subject when trying to generate lineups for this weekends NFL games. Once I click OK I get another error. Any clue what this is happening? Thanks.

![capture](https://cloud.githubusercontent.com/assets/25187724/22044259/ca6acc48-dce1-11e6-91cf-b1c842f7897b.PNG)

![opensolver](https://cloud.githubusercontent.com/assets/25187724/22044267/cfa4063e-dce1-11e6-8648-3b136ade0caf.PNG)

**Comment by pherny** [comment]
please ignore I found the issue. Thank you!

**Comment by scipio314** [comment]
what did you do to fix it in case someone else has this issue?

**Comment by pherny** [comment]
I had to unhide the All Players sheet and remove data from all cells containing #N/A. This was done after I added the player pool. Please see below.

![fix](https://cloud.githubusercontent.com/assets/25187724/22065179/04089ea8-dd55-11e6-9fd6-463c11a197b7.PNG)
